# Generated by Django 2.2 on 2019-04-18 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20190418_2146'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExampleUser',
            new_name='User',
        ),
    ]
